pygments: true
url: http://www.pongasoft.com/blog/yan
permalink: pretty
category_title_prefix: ''
exclude: ['jkdev.sh']
mainColor1: '#005a87'
mainColor2: '#0075b0'
contentBGColor: '#eeeeee'
contentFGColor: 'black'
titleBGColor: 'maroon'
titleFGColor: 'white'
contentFontFamily: 'Helvetica,Arial,sans-serif'
monospaceFontFamily: 'Courier New,monospace'
dateBackgroundColor: '#888888'
