# jekyll related entries
url: https://www.pongasoft.com/blog/yan
permalink: pretty
category_title_prefix: ''
exclude: ['jkdev.sh', 'brokenbits-blog.iml']

# css related entries
mainColor1: '#005a87'
mainColor2: '#244353'
contentBGColor: '#eeeeee'
contentFGColor: 'black'
titleBGColor: '#600000'
titleFGColor: 'white'
contentFontFamily: 'Arial,Helvetica,sans-serif'
monospaceFontFamily: 'Courier New,monospace'
dateBackgroundColor: '#888888'

# since jekyll 3.7.2...
plugins:
- jekyll-textile-converter

# post related entries
withTwitter: true
withGoogle: true
prodMode: true