# jekyll related entries
highlighter: pygments
url: https://www.pongasoft.com/blog/yan
permalink: pretty
category_title_prefix: ''
exclude: ['jkdev.sh', 'brokenbits-blog.iml']

# css related entries
mainColor1: '#005a87'
mainColor2: '#0075b0'
contentBGColor: '#eeeeee'
contentFGColor: 'black'
titleBGColor: '#600000'
titleFGColor: 'white'
contentFontFamily: 'Helvetica,Arial,sans-serif'
monospaceFontFamily: 'Courier New,monospace'
dateBackgroundColor: '#888888'

# since jekyll 3.0...
gems:
- jekyll-textile-converter

# post related entries
withLinkedIn: true
withTwitter: true
withComments: false
withGoogle: true
prodMode: true