# jekyll related entries
pygments: true
url: http://www.pongasoft.com/blog/yan
permalink: pretty
category_title_prefix: ''
exclude: ['jkdev.sh', 'brokenbits-blog.iml']

# css related entries
mainColor1: '#005a87'
mainColor2: '#0075b0'
contentBGColor: '#eeeeee'
contentFGColor: 'black'
titleBGColor: '#600000'
titleFGColor: 'white'
contentFontFamily: 'Helvetica,Arial,sans-serif'
monospaceFontFamily: 'Courier New,monospace'
dateBackgroundColor: '#888888'

# post related entries
withLinkedIn: true
withTweeter: true
withComments: true
withGoogle: true
prodMode: true